
'''Default configuration file generated by NayseDog'''

from nayesdog.config import get_name_in_library, DEFAULTCONFIGPATH 

feeds_url_dict = {
    'Nature Research': 'http://feeds.nature.com/NatureLatestResearch',
    'Arstechnica': 'http://feeds.arstechnica.com/arstechnica/science',
    'IEEE': 'http://spectrum.ieee.org/rss/fulltext',
    'Nature News': (
        'HTML',
        'http://www.nature.com/news/index.html',
        'https?://[^/]+nature.com/news/[^"]+',
        "sp.find('section', attrs={'id': 'article-body'})",
        '',
     ),
    'Science': (
        'HTML',                                                    # Type of parser
        'http://www.sciencemag.org/news',                          # url with links to news items, MASTER page
        '/news/[0-9]{4}/[0-9]{1,2}/[^"]+',                         # regex for links to news items
        "sp.find('article', attrs={'class': 'primary--content'})", # if I follow a link, which HTML element contains useful content
        'http://www.sciencemag.org',                               # Prefix to prepend to each paresed link from MASTER page
     ),
    'MIT Technology Review': (
        'HTML',
        'https://www.technologyreview.com/daily/',
        '/s/[^/]+/[^"]+',
        "sp.find('div', attrs={'class': 'article-body__content'})",
        'https://www.technologyreview.com',
    )
} 

word_counts_database_file           = DEFAULTCONFIGPATH + '/tables.py.gz'
previous_session_database_file      = DEFAULTCONFIGPATH + '/previous_session'
maximal_number_of_entries_in_memory = 5000

stopwords_file                      = get_name_in_library('stopwords.txt')
server_address                      = ('127.0.0.1', 8081)

cssfile                             = DEFAULTCONFIGPATH + '/style/css.css'
icons_folder                        = DEFAULTCONFIGPATH + "/style/icons"
